import type { StorefrontForm } from "@/types/storefront";

export const defaultStorefrontForm: StorefrontForm = {
  name: "",
  slogan: "",
  primary_color: "#6366f1",
  hero_image_url: "",
  hero_video_url: "",
  about_text_fr: "",
  about_text_en: "",
  about_text_ar: "",
  sections_config: {
    featured: true,
    stats: true,
    why_us: true,
    testimonials: true,
    map: true,
    vibe_selector: true,
    lifestyle_gallery: true,
    faq: true,
    concierge_banner: true,
  },
  sections_order: [
    { id: "hero", label: "Bannière Hero", active: true },
    { id: "stats", label: "Statistiques Clés", active: true },
    { id: "featured", label: "Véhicules Vedettes", active: true },
    { id: "why_us", label: "Nos Avantages", active: true },
    { id: "testimonials", label: "Témoignages", active: true },
    { id: "vibe_selector", label: "Sélecteur d'Expérience (Vibe)", active: true },
    { id: "lifestyle_gallery", label: "Galerie Lifestyle (Parallaxe)", active: true },
    { id: "map", label: "Localisation & Map", active: true },
    { id: "concierge_banner", label: "Bannière Concierge IA", active: true },
    { id: "faq", label: "Foire Aux Questions (Accordéon)", active: true },
    { id: "how_it_works", label: "Comment ça marche", active: true },
    { id: "cta_banner", label: "Bannière d'Appel à l'Action", active: true },
  ],
  testimonials: [],
  seo_config: { title: "", description: "", keywords: "", og_image: "" },
  category_prices: { eco: 250, standard: 350, suv: 600, luxury: 1200, sport: 1000 },
  special_offers: [],
  header_config: { sticky: true, transparent_hero: true, menu_links: [] },
  footer_config: { address: "", phone: "", email: "", social_links: { facebook: "", instagram: "", whatsapp: "" } },
  theme_config: { border_radius: "24px", button_style: "pill", glassmorphism: true, font_family: "Inter" },
  stats_config: {
    label_1: "Clients Satisfaits", value_1: "2,400+",
    label_2: "Véhicules Premium", value_2: "80+",
    label_3: "Années d'Excellence", value_3: "15",
    label_4: "Support VIP", value_4: "24/7",
  },
  faq_config: [
    { q: "Quelles sont les conditions de location ?", a: "Vous devez être âgé de 21 ans minimum et posséder un permis de conduire valide depuis au moins 2 ans." },
    { q: "Proposez-vous la livraison à l'hôtel ?", a: "Oui, nous livrons nos véhicules gratuitement dans tous les hôtels et aéroports des villes où nous sommes présents." },
  ],
  features_config: [
    { icon: "Crown", title: "Flotte d'Exception", desc: "Une sélection rigoureuse des modèles les plus prestigieux du marché." },
    { icon: "ShieldCheck", title: "Assurance Premium", desc: "Roulez en toute sérénité avec nos couvertures tous risques incluses." },
    { icon: "HeadphonesIcon", title: "Service Conciergerie", desc: "Une assistance personnalisée disponible 24h/7j pour tous vos besoins." },
  ],
  concierge_config: { title: "Conciergerie Digitale", text: "Besoin d'un itinéraire ou d'un conseil ? Notre IA vous accompagne." },
  sections_content: {
    hero: { badge: "Collection Exclusive 2026", title: "L'excellence en mouvement.", subtitle: "Découvrez une nouvelle dimension du voyage avec notre flotte de prestige." },
    why_us: { title: "Pourquoi choisir Vectoria ?", subtitle: "Nous redéfinissons les standards de la location de luxe au Maroc." },
    vibe: { title: "Quelle est votre vibe aujourd'hui ?", subtitle: "Choisissez l'émotion qui guidera votre prochain voyage." },
    lifestyle: { title: "Bien plus qu'un simple trajet.", subtitle: "L'Expérience", text: "Nous intégrons chaque voyage dans un style de vie d'exception." },
    faq: { title: "Questions Fréquentes", subtitle: "Tout ce que vous devez savoir pour votre location." },
  },
};
