import type { StorefrontForm } from "@/types/storefront";

export const defaultStorefrontForm: StorefrontForm = {
  name: "",
  slogan: "",
  primary_color: "#6366f1",
  logo_url: "",
  hero_image_url: "",
  hero_video_url: "",
  about_text_fr: "",
  about_text_en: "",
  about_text_ar: "",
  sections_config: {
    featured: true,
    stats: true,
    why_us: true,
    testimonials: true,
    map: true,
    vibe_selector: true,
    lifestyle_gallery: true,
    faq: true,
    concierge_banner: true,
    experience: true,
    how_it_works: true,
    cta_banner: true,
    promotion_banner: true,
    dual_cta: true,
    comparator: true,
  },
  sections_order: [
    { id: "hero", label: "Bannière Hero", active: true },
    { id: "trust_bar", label: "Avantages & Support VIP", active: true },
    { id: "featured", label: "Véhicules Vedettes", active: true },
    { id: "why_us", label: "Nos Avantages", active: true },
    { id: "testimonials", label: "Témoignages", active: true },
    { id: "vibe_selector", label: "Sélecteur d'Expérience (Vibe)", active: true },
    { id: "lifestyle_gallery", label: "Galerie Lifestyle (Parallaxe)", active: true },
    { id: "map", label: "Localisation & Map", active: true },
    { id: "concierge_banner", label: "Bannière Concierge IA", active: true },
    { id: "faq", label: "Foire Aux Questions (Accordéon)", active: true },
    { id: "how_it_works", label: "Comment ça marche", active: true },
    { id: "dual_cta", label: "Double Appel à l'Action", active: true },
    { id: "comparator", label: "Le Garage Comparateur", active: true },
    { id: "fleet", label: "Page Flotte (Fleet)", active: true },
  ],
  testimonials: [],
  seo_config: { title: "", description: "", keywords: "", og_image: "" },
  category_prices: { eco: 250, standard: 350, suv: 600, luxury: 1200, sport: 1000 },
  special_offers: [],
  header_config: { sticky: true, transparent_hero: true, menu_links: [] },
  footer_config: { address: "", phone: "", email: "", social_links: { facebook: "", instagram: "", whatsapp: "" } },
  theme_config: { border_radius: "24px", button_style: "pill", glassmorphism: true, font_family: "Inter" },
  stats_config: {
    columns: "6",
    theme: "light",
    height: "normal",
    text_size: "normal",
    text_color: "",
    items: [
      { id: "s1", label: "24/7 Assistance", value: "", icon: "Clock" },
      { id: "s2", label: "Airport Delivery", value: "", icon: "Car" },
      { id: "s3", label: "Unlimited Mileage", value: "", icon: "Target" },
      { id: "s4", label: "Insurance Included", value: "", icon: "Shield" },
      { id: "s5", label: "Transparent Pricing", value: "", icon: "CreditCard" },
      { id: "s6", label: "Fast Booking", value: "", icon: "Zap" }
    ]
  },
  faq_config: [
    { q: "Quelles sont les conditions de location ?", a: "Vous devez être âgé de 21 ans minimum et posséder un permis de conduire valide depuis au moins 2 ans." },
    { q: "Proposez-vous la livraison à l'hôtel ?", a: "Oui, nous livrons nos véhicules gratuitement dans tous les hôtels et aéroports des villes où nous sommes présents." },
  ],
  features_config: [
    { icon: "Crown", title: "Flotte d'Exception", desc: "Une sélection rigoureuse des modèles les plus prestigieux du marché." },
    { icon: "ShieldCheck", title: "Assurance Premium", desc: "Roulez en toute sérénité avec nos couvertures tous risques incluses." },
    { icon: "HeadphonesIcon", title: "Service Conciergerie", desc: "Une assistance personnalisée disponible 24h/7j pour tous vos besoins." },
  ],
  concierge_config: { title: "Conciergerie Digitale", text: "Besoin d'un itinéraire ou d'un conseil ? Notre IA vous accompagne." },
  sections_content: {
    hero: {
      badge: "— PREMIUM CAR RENTAL • MOROCCO",
      title: "Drive Morocco with confidence, not compromise.",
      subtitle: "A modern fleet, transparent pricing, and airport-ready delivery — built for business travel, family trips, and everything in between.",
      cta_text: "Browse the fleet",
      cta_link: "/fleet",
      rating_text: "4.9 / 5 on Google · 2,300+ rentals",
      benefits: [
        { icon: "Headphones", text: "Support VIP 24/7" },
        { icon: "ShieldCheck", text: "Assurance Tous Risques" },
        { icon: "Car", text: "Livraison Aéroport" }
      ]
    },
    why_us: { 
      title: "Pourquoi choisir Vectoria ?", 
      subtitle: "Nous redéfinissons les standards de la location de luxe au Maroc.",
      features: [
        { icon: "Crown", title: "Flotte d'Exception", desc: "Une sélection rigoureuse des modèles les plus prestigieux du marché." },
        { icon: "ShieldCheck", title: "Assurance Premium", desc: "Roulez en toute sérénité avec nos couvertures tous risques incluses." },
        { icon: "HeadphonesIcon", title: "Service Conciergerie", desc: "Une assistance personnalisée disponible 24h/7j pour tous vos besoins." },
      ]
    },
    vibe: { 
      title: "Quelle est votre vibe aujourd'hui ?", 
      subtitle: "Choisissez l'émotion qui guidera votre prochain voyage.", 
      eyebrow: "Expérience Sur Mesure",
      columns: "4",
      items: [
        { id: "business", title: "Business Elite", subtitle: "Prestige & Stratégie", icon: "ShieldCheck", image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&q=80&w=800", color_from: "primary", color_via: "primary", lifestyle: "business" },
        { id: "romance", title: "Grand Tourisme", subtitle: "Émotion & Liberté", icon: "Wind", image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800", color_from: "rose-500", color_via: "orange-500", lifestyle: "romance" },
        { id: "aventure", title: "Wild Adventure", subtitle: "Puissance & Exploration", icon: "Mountain", image: "https://images.unsplash.com/photo-1535704882196-765e5fc62a53?auto=format&fit=crop&q=80&w=800", color_from: "emerald-600", color_via: "teal-600", lifestyle: "adventure" },
        { id: "family", title: "Family First", subtitle: "Confort & Partage", icon: "Zap", image: "https://images.unsplash.com/photo-1549113294-313d8bc63a4c?auto=format&fit=crop&q=80&w=800", color_from: "gold", color_via: "gold", lifestyle: "family" }
      ]
    },
    lifestyle: { title: "Bien plus qu'un simple trajet.", subtitle: "L'Expérience", text: "Nous intégrons chaque voyage dans un style de vie d'exception." },
    faq: { title: "Questions Fréquentes", subtitle: "Tout ce que vous devez savoir pour votre location.", badge: "Support Client", contact_text: "Vous avez encore des questions ?", contact_link: "/contact" },
    experience: { eyebrow: "L'Expérience Premium", title_line1: "Bien plus qu'un", title_line2: "simple trajet.", description: "Nous redéfinissons la mobilité de luxe.", cta_text: "Voir toute la collection", cta_link: "/fleet", stats: [{ value: "98%", label: "Recommandation" }, { value: "24/7", label: "Support VIP" }], lifestyles: [{ id: "business", title: "Business Elite", subtitle: "Ponctualité et prestige", icon: "Shield", image: "", color_from: "blue-400", color_via: "blue-600", lifestyle: "business" }] },
    how_it_works: { badge: "Simple & Rapide", steps: [] },
    cta_banner: { eyebrow: "Prêt à prendre le volant ?", button_text: "Découvrir la flotte", button_link: "/fleet" },
    promotion_banner: { badge: "Programme Privilège", title_line1: "L'exclusivité au", title_line2: "bout des doigts.", description: "Accédez à des tarifs préférentiels.", cta_text: "Rejoindre le cercle", cta_link: "/register", side_note: "Inscription gratuite", footer_items: ["Paiement sécurisé", "Conciergerie 24/7"] },
    testimonials: { badge: "Avis Clients", heading: "Ce que disent nos clients", description: "Découvrez les expériences." },
    map: { badge: "Présence Nationale", slogan: "Une sélection de prestige.", locations: [] },
    comparator: { badge: "Le Garage Comparateur", title: "Confrontez l'Excellence.", subtitle: "Choisissez deux modèles.", vs_label: "VS", vehicles: [] },
    sticky_booking: { placeholder: "Destination", search_label: "Rechercher" },
    featured_vehicles: { eyebrow: "Showroom", cta_text: "Voir le catalogue", cta_link: "/fleet", loading_text: "Chargement...", empty_heading: "Aucun véhicule", empty_description: "Bientôt disponible" },
    search_form: { form_title: "Reserve your vehicle", form_subtitle: "Confirmed in under 2 minutes.", location_label: "Destination", location_placeholder: "Ville, aéroport...", start_label: "Départ", end_label: "Retour", search_button: "Check availability", fleet_link_text: "Voir toute la flotte", fleet_link_href: "/fleet" },
    fleet: {
      hero_image: "",
      hero_badge: "Premium Fleet",
      hero_title: "Explore Our Vehicle Fleet",
      hero_subtitle: "Find the perfect vehicle for business trips, family vacations and luxury experiences across Morocco.",
      search_button_text: "Search",
      default_location: "Casablanca — Mohammed V Airport",
      results_text: "Vehicles Found",
      sort_label: "Sort by:",
      default_sort: "recommended",
      filters_layout: "vertical",
      page_size: 10,
      columns: 3,
      empty_title: "No vehicles found",
      empty_description: "Try adjusting your filters to see more results.",
      load_more_text: "Load More",
    },
  },
};
