server {
    listen 80;
    server_name localhost;
    root /var/www/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    # API Backend
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Storage for images
    location /storage {
        alias /var/www/storage/app/public;
        try_files $uri =404;
    }

    # PHP-FPM
    location ~ \.php$ {
        resolver 127.0.0.11 valid=30s;
        set $backend backend:9000;
        fastcgi_pass $backend;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Frontend Proxy (Next.js)
    location / {
        resolver 127.0.0.11 valid=30s;
        set $frontend http://frontend:3000;
        proxy_pass $frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
