<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $agent = User::where('role', 'agent')->first();
        $agentId = $agent?->id;

        $vehicles = [
            [
                'brand' => 'Range Rover',
                'model' => 'Sport HSE',
                'plate' => '12345-A-1',
                'price_per_day' => 1800.00,
                'mileage' => 12500,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'horsepower' => 300,
                'year' => 2024,
                'color' => 'Eiger Gray',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1606016159991-dfe4f974be5c?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Range Rover Sport HSE dynamique et raffiné, parfait pour la ville et les longs trajets.',
                'description_en' => 'Dynamic and refined Range Rover Sport HSE, perfect for city and long distance travel.',
                'description_ar' => 'رانج روفر سبورت إتش إس إي ديناميكية وراقية، مثالية للمدينة والرحلات الطويلة.',
            ],
            [
                'brand' => 'Mercedes-Benz',
                'model' => 'G63 AMG',
                'plate' => '67890-B-26',
                'price_per_day' => 3500.00,
                'mileage' => 8400,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'luxury',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 585,
                'year' => 2023,
                'color' => 'Obsidian Black',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1520050206274-a1ae446cb3cc?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Légendaire Classe G AMG avec moteur V8 bi-turbo. Puissance, confort et présence imposante.',
                'description_en' => 'Legendary G-Class AMG with V8 bi-turbo engine. Power, comfort, and commanding presence.',
                'description_ar' => 'مرسيدس جي كلاس إيه إم جي الأسطورية بمحرك V8 ثنائي التيربو. قوة وراحة وحضور مهيب.',
            ],
            [
                'brand' => 'Porsche',
                'model' => '911 Carrera S',
                'plate' => '11223-D-7',
                'price_per_day' => 2800.00,
                'mileage' => 4500,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'sport',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 450,
                'year' => 2024,
                'color' => 'Crayon Gray',
                'seats' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'La sportive de référence. Agilité exceptionnelle, accélération fulgurante et design intemporel.',
                'description_en' => 'The benchmark sports car. Exceptional agility, lightning acceleration, and timeless design.',
                'description_ar' => 'بورش 911 كاريرا إس، المرجعية في السيارات الرياضية. مرونة استثنائية وتصميم خالد.',
            ],
            [
                'brand' => 'Ferrari',
                'model' => 'F8 Tributo',
                'plate' => '44556-H-8',
                'price_per_day' => 6500.00,
                'mileage' => 2100,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'sport',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 720,
                'year' => 2023,
                'color' => 'Rosso Corsa',
                'seats' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Supercar italienne ultime équipée du V8 le plus puissant de la marque. Performances extrêmes.',
                'description_en' => 'The ultimate Italian supercar equipped with the brands most powerful V8. Extreme performance.',
                'description_ar' => 'فيراري إف 8 تريبوتو، السيارة الخارقة المثالية بمحرك V8 الأكثر قوة في تاريخ العلامة.',
            ],
            [
                'brand' => 'Audi',
                'model' => 'RS6 Avant',
                'plate' => '77889-J-12',
                'price_per_day' => 2400.00,
                'mileage' => 14800,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'sport',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 600,
                'year' => 2024,
                'color' => 'Nardo Gray',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Le break de chasse surpuissant. Un équilibre parfait entre praticité familiale et performances sauvages.',
                'description_en' => 'The ultra-powerful super estate. A perfect balance of family practicality and wild performance.',
                'description_ar' => 'أودي آر إس 6 أفانت، سيارة عائلية خارقة القوة تجمع بين العملية والأداء الرياضي الشرس.',
            ],
            [
                'brand' => 'BMW',
                'model' => 'M5 Competition',
                'plate' => '99001-K-15',
                'price_per_day' => 2200.00,
                'mileage' => 19500,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'luxury',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 625,
                'year' => 2023,
                'color' => 'Marina Bay Blue',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Berline de luxe haute performance. La précision allemande alliée à une puissance brute remarquable.',
                'description_en' => 'High-performance luxury sedan. German precision combined with remarkable raw power.',
                'description_ar' => 'بي إم دبليو إم 5 كومبتيشن، سيدان فاخرة عالية الأداء تتميز بالدقة الألمانية والقوة المذهلة.',
            ],
            [
                'brand' => 'Tesla',
                'model' => 'Model S Plaid',
                'plate' => '22334-L-3',
                'price_per_day' => 1500.00,
                'mileage' => 21800,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'eco',
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'horsepower' => 1020,
                'year' => 2023,
                'color' => 'Solid Black',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Berline électrique révolutionnaire avec plus de 1000 chevaux. Accélération de 0 à 100 km/h en 2,1s.',
                'description_en' => 'Revolutionary electric sedan with over 1000 hp. 0-100 km/h acceleration in 2.1s.',
                'description_ar' => 'تيسلا موديل إس بلايد، سيدان كهربائية ثورية بقوة تزيد عن 1000 حصان وتسارع مذهل.',
            ],
            [
                'brand' => 'Bentley',
                'model' => 'Bentayga V8',
                'plate' => '55667-M-20',
                'price_per_day' => 4800.00,
                'mileage' => 9700,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'luxury',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 550,
                'year' => 2023,
                'color' => 'British Green',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'SUV ultra-luxueux alliant artisanat britannique fait main et performances dynamiques exceptionnelles.',
                'description_en' => 'Ultra-luxurious SUV combining handmade British craftsmanship with exceptional performance.',
                'description_ar' => 'بنتلي بنتايجا، سيارة رياضية متعددة الاستخدامات فائقة الفخامة تجمع بين الحرفية البريطانية والقوة.',
            ],
            [
                'brand' => 'Lamborghini',
                'model' => 'Urus S',
                'plate' => '88990-N-26',
                'price_per_day' => 4000.00,
                'mileage' => 7100,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 666,
                'year' => 2024,
                'color' => 'Giallo Auge',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Le Super SUV de Lamborghini. L’âme d’une supersportive et la fonctionnalité d’un SUV.',
                'description_en' => 'Lamborghini Super SUV. The soul of a super sports car and the functionality of an SUV.',
                'description_ar' => 'لامبورغيني أوروس إس، سيارة الدفع الرباعي الفائقة بروح سيارة رياضية خارقة وعملية سيارة SUV.',
            ],
            [
                'brand' => 'Rolls-Royce',
                'model' => 'Ghost V12',
                'plate' => '12131-P-9',
                'price_per_day' => 8500.00,
                'mileage' => 5200,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'luxury',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 571,
                'year' => 2023,
                'color' => 'English White',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Le summum du luxe automobile. Un silence absolu et un confort inégalable, comme sur un tapis volant.',
                'description_en' => 'The pinnacle of automotive luxury. Absolute silence and incomparable comfort, like a magic carpet ride.',
                'description_ar' => 'رولز رويس غوست، قمة الفخامة في عالم السيارات. هدوء مطلق وراحة لا مثيل لها.',
            ],
            [
                'brand' => 'Mercedes-Benz',
                'model' => 'S-Class 400d',
                'plate' => '33445-Q-1',
                'price_per_day' => 2500.00,
                'mileage' => 11200,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'luxury',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'horsepower' => 330,
                'year' => 2024,
                'color' => 'Selenite Gray',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'La limousine de référence mondiale. Technologie de pointe, confort et raffinement incomparables.',
                'description_en' => 'The world-reference luxury limousine. Advanced technology, incomparable comfort and refinement.',
                'description_ar' => 'مرسيدس بنز الفئة إس، مرجع الليموزين العالمي. تكنولوجيا متقدمة وراحة فائقة.',
            ],
            [
                'brand' => 'Porsche',
                'model' => 'Cayenne Coupe',
                'plate' => '55668-R-7',
                'price_per_day' => 1900.00,
                'mileage' => 10200,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'horsepower' => 470,
                'year' => 2024,
                'color' => 'Carrara White',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Un SUV coupé élégant et puissant équipé d’une motorisation hybride performante.',
                'description_en' => 'An elegant and powerful SUV coupe equipped with a high-performance hybrid powertrain.',
                'description_ar' => 'بورش كايين كوبيه، سيارة رياضية متعددة الاستخدامات أنيقة وقوية بمحرك هجين متطور.',
            ],
            [
                'brand' => 'Audi',
                'model' => 'Q8 S-Line',
                'plate' => '77890-S-26',
                'price_per_day' => 1400.00,
                'mileage' => 18300,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'horsepower' => 286,
                'year' => 2024,
                'color' => 'Daytona Gray',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'SUV coupé imposant combinant design sportif, habitacle luxueux et technologies modernes.',
                'description_en' => 'Commanding SUV coupe combining sporty design, luxurious interior, and modern technologies.',
                'description_ar' => 'أودي كيو 8 إس لاين، تصميم كوبيه جذاب مع مقصورة داخلية فاخرة وأنظمة ذكية.',
            ],
            [
                'brand' => 'BMW',
                'model' => 'X7 M60i',
                'plate' => '99002-T-15',
                'price_per_day' => 2000.00,
                'mileage' => 13400,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'horsepower' => 340,
                'year' => 2024,
                'color' => 'Carbon Black',
                'seats' => 7,
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Le plus grand SUV de BMW offrant 7 places dans un luxe digne d’une Classe Executive.',
                'description_en' => 'BMWs largest SUV offering 7 seats in executive class luxury.',
                'description_ar' => 'بي إم دبليو إكس 7، سيارة دفع رباعي ضخمة تتسع لـ 7 مقاعد بفخامة متناهية.',
            ],
            [
                'brand' => 'Mercedes-Benz',
                'model' => 'E-Class Coupe',
                'plate' => '11224-U-1',
                'price_per_day' => 1200.00,
                'mileage' => 24800,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'standard',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'horsepower' => 245,
                'year' => 2023,
                'color' => 'Polar White',
                'seats' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Coupé élégant et dynamique, idéal pour voyager avec style et confort.',
                'description_en' => 'Elegant and dynamic coupe, ideal for traveling with style and comfort.',
                'description_ar' => 'مرسيدس الفئة إي كوبيه، سيارة أنيقة ومثيرة، رائعة للسفر براحة وأناقة.',
            ],
            [
                'brand' => 'Range Rover',
                'model' => 'Velar R-Dynamic',
                'plate' => '44557-V-26',
                'price_per_day' => 1300.00,
                'mileage' => 27500,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'horsepower' => 204,
                'year' => 2023,
                'color' => 'Byron Blue',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1606016159991-dfe4f974be5c?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Design minimaliste avant-gardiste et technologies de pointe pour ce SUV moderne et raffiné.',
                'description_en' => 'Avant-garde minimalist design and cutting-edge technologies in this modern and refined SUV.',
                'description_ar' => 'رانج روفر فيلار بتصميمها العصري البسيط والتكنولوجيا الحديثة الفائقة.',
            ],
            [
                'brand' => 'Porsche',
                'model' => 'Panamera E-Hybrid',
                'plate' => '77891-W-7',
                'price_per_day' => 2100.00,
                'mileage' => 17200,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'luxury',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'horsepower' => 462,
                'year' => 2023,
                'color' => 'Jet Black',
                'seats' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Berline de luxe offrant les performances d’une authentique sportive Porsche.',
                'description_en' => 'Luxury sedan offering the performance of an authentic Porsche sports car.',
                'description_ar' => 'بورش باناميرا إي-هيبريد، سيدان رياضية فاخرة تجمع بين قوة بورش واقتصاد الهجين.',
            ],
            [
                'brand' => 'Ferrari',
                'model' => 'Roma V8',
                'plate' => '99003-X-8',
                'price_per_day' => 5500.00,
                'mileage' => 3700,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'sport',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 620,
                'year' => 2023,
                'color' => 'Grigio Silverstone',
                'seats' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Le nouveau coupé 2+ de Maranello arborant un style néo-rétro élégant inspiré de la Dolce Vita.',
                'description_en' => 'The new 2+ coupe from Maranello displaying elegant neo-retro styling inspired by the Dolce Vita.',
                'description_ar' => 'فيراري روما، كوبيه مذهل بتصميم ريترو ساحر مستوحى من نمط الحياة الإيطالية الكلاسيكية.',
            ],
            [
                'brand' => 'Aston Martin',
                'model' => 'DBX 707',
                'plate' => '22335-Y-26',
                'price_per_day' => 3800.00,
                'mileage' => 8100,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'suv',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'horsepower' => 707,
                'year' => 2023,
                'color' => 'Xenon Gray',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Le SUV le plus puissant et luxueux d’Aston Martin. Un monstre de route habillé de haute couture.',
                'description_en' => 'Aston Martins most powerful and luxurious SUV. A road monster dressed in high fashion.',
                'description_ar' => 'أستون مارتن دي بي إكس 707، سيارة الدفع الرباعي الفاخرة الأقوى بمظهر رياضي وتصميم جذاب.',
            ],
            [
                'brand' => 'Audi',
                'model' => 'e-tron GT',
                'plate' => '55669-Z-26',
                'price_per_day' => 1600.00,
                'mileage' => 5900,
                'status' => 'available',
                'agent_id' => $agentId,
                'type' => 'internal',
                'category' => 'eco',
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'horsepower' => 530,
                'year' => 2024,
                'color' => 'Kemora Gray',
                'seats' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=800',
                'description_fr' => 'Berline grand tourisme 100% électrique au design athlétique. Une recharge ultra-rapide et un confort impérial.',
                'description_en' => '100% electric grand tourer sedan with an athletic design. Ultra-fast charging and imperial comfort.',
                'description_ar' => 'أودي إي ترون جي تي، سيدان رياضية كهربائية بالكامل تجمع بين الأداء والتصميم المستقبلي الراقي.',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            \DB::table('vehicles')->updateOrInsert(
                ['plate' => $vehicle['plate']],
                array_merge($vehicle, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
